compute_environment: LOCAL_MACHINE
deepspeed_config:
  deepspeed_config_file: configs/accelerate/deepspeed/ds_config_zero3_offload.json
  zero3_init_flag: false
distributed_type: DEEPSPEED
downcast_bf16: 'no'
machine_rank: 0
main_training_function: main
num_machines: 1
num_processes: 8
rdzv_backend: static
use_cpu: false