compute_environment: LOCAL_MACHINE
deepspeed_config: {}
distributed_type: MULTI_GPU
downcast_bf16: 'no'
fsdp_config: {}
machine_rank: 0
main_process_ip: null
main_process_port: 11922
main_training_function: main
mixed_precision: 'fp16'
num_machines: 1
num_processes: 8
use_cpu: false