DATA:
  IMG_SIZE: 512
  IMG_ON_MEMORY: True
AUG:
  MIXUP: 0.0
  CUTMIX: 0.0
  REPROB: 0.0
MODEL:
  TYPE: intern_image
  DROP_PATH_RATE: 0.4
  LABEL_SMOOTHING: 0.3
  INTERN_IMAGE:
    CORE_OP: 'DCNv3'
    DEPTHS: [2, 2, 48, 4]
    GROUPS: [16, 32, 64, 128]
    CHANNELS: 512
    DW_KERNEL_SIZE: 5
    LAYER_SCALE: None
    OFFSET_SCALE: 1.0
    MLP_RATIO: 4.0
    POST_NORM: True
    LEVEL2_POST_NORM: True
    LEVEL2_POST_NORM_BLOCK_IDS: [5, 11, 17, 23, 29, 35, 41, 47]
    CENTER_FEATURE_SCALE: True
    USE_CLIP_PROJECTOR: True
TRAIN:
  EMA:
    ENABLE: true
    DECAY: 0.9999
  EPOCHS: 20
  WARMUP_EPOCHS: 2
  WEIGHT_DECAY: 0.05
  BASE_LR: 2e-05 # 512
  WARMUP_LR: .0
  MIN_LR: .0
  LR_LAYER_DECAY: true
  LR_LAYER_DECAY_RATIO: 0.9
  USE_CHECKPOINT: true
  OPTIMIZER:
    DCN_LR_MUL: 0.1
AMP_OPT_LEVEL: O0
EVAL_FREQ: 1